# Generated by Django 5.0.1 on 2024-03-06 12:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('blogId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('membersId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uName', models.CharField(blank=True, max_length=100, null=True)),
                ('uEmail', models.EmailField(max_length=100, null=True, unique=True)),
                ('uPass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('commentersName', models.CharField(max_length=100)),
                ('commentContent', models.TextField(max_length=300)),
                ('commentDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('abc', models.CharField(max_length=100)),
                ('blog_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.blog')),
                ('membersId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.members')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='membersId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.members'),
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('blogId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.members')),
            ],
        ),
    ]
