# Generated by Django 5.0.1 on 2024-02-20 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('membersId', models.IntegerField(primary_key=True, serialize=False)),
                ('uName', models.CharField(max_length=100)),
                ('uEmail', models.EmailField(max_length=100, unique=True)),
                ('uPass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='commants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(max_length=1000)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.members')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.members')),
            ],
        ),
    ]
