# Generated by Django 5.0.1 on 2024-02-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='commants',
            new_name='comments',
        ),
    ]
