# Generated by Django 5.0.1 on 2024-03-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='abc',
        ),
    ]
