# Generated by Django 5.0.1 on 2024-03-07 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_members_upass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='images',
        ),
    ]
