# Generated by Django 5.0.1 on 2024-02-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_remove_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='members',
            name='membersId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
