# Generated by Django 5.0.1 on 2024-03-05 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_blog_id_alter_members_membersid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='css/images'),
        ),
        migrations.AddField(
            model_name='blog',
            name='membersId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.members'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
