# Generated by Django 5.0.1 on 2024-03-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_blog_image_blog_membersid_alter_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='css/images'),
        ),
    ]
