# Generated by Django 5.0.1 on 2024-03-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_blog_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='images',
            field=models.ImageField(upload_to='page/images/'),
        ),
    ]
