# Generated by Django 5.0.1 on 2024-03-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_alter_blog_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='images',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
    ]
