# Generated by Django 5.0.1 on 2024-03-07 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_members_images_alter_blog_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='members_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(blank=True, related_name='following_users', to='page.members')),
                ('following', models.ManyToManyField(blank=True, related_name='followers_users', to='page.members')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page.members')),
            ],
        ),
    ]
