# Generated by Django 5.0.1 on 2024-03-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_members_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='uabout',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
