# Generated by Django 5.0.1 on 2024-03-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_members_uabout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentersName',
        ),
    ]
