# Generated by Django 5.0.1 on 2024-03-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_alter_blog_image_alter_members_membersid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='uEmail',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
