# Generated by Django 5.0.1 on 2024-03-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_comment_commentersname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentersName',
        ),
    ]
