# Generated by Django 5.0.1 on 2024-03-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_alter_members_uemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
