# Generated by Django 5.0.1 on 2024-03-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_remove_comment_commentersname'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentersName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
