# Generated by Django 5.0.1 on 2024-03-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_alter_blog_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentersName',
            new_name='commenterName',
        ),
    ]
