# Generated by Django 5.0.1 on 2024-03-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_rename_commentersname_comment_commentername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='images',
        ),
    ]
