# Generated by Django 5.0.1 on 2024-03-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_rename_commentername_comment_commentersname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='images',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
