# Generated by Django 5.0.1 on 2024-03-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_members_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='forgetPassToken',
        ),
    ]
