# Generated by Django 5.0.1 on 2024-03-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_remove_members_forgetpasstoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='uabout',
            new_name='about',
        ),
    ]
