# Generated by Django 5.0.1 on 2024-03-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0020_rename_uabout_members_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='images',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
