# Generated by Django 5.0.1 on 2024-03-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0021_alter_members_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentersName',
        ),
    ]
