# Generated by Django 5.0.1 on 2024-03-14 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0022_remove_comment_commentersname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentContent',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='members_profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to='page.members'),
        ),
        migrations.AlterField(
            model_name='members_profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to='page.members'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
