# Generated by Django 5.0.1 on 2024-03-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0024_alter_comment_commentcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentContent',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
