# Generated by Django 5.0.1 on 2024-03-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0025_alter_comment_commentcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='ratingvalue',
        ),
    ]
