# Generated by Django 5.0.1 on 2024-03-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0026_rename_rating_rating_ratingvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='forgetPassToken',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
