# Generated by Django 5.0.1 on 2024-03-18 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0027_members_forgetpasstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to='page.members')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page.members')),
            ],
        ),
        migrations.DeleteModel(
            name='members_profile',
        ),
    ]
