# Generated by Django 5.0.1 on 2024-03-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0028_userprofile_delete_members_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followers',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='another_user',
            field=models.ManyToManyField(blank=True, related_name='another_user', to='page.members'),
        ),
    ]
