# Generated by Django 5.0.1 on 2024-03-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0034_alter_userprofile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='page.members'),
        ),
    ]
