# Generated by Django 5.0.1 on 2024-03-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0036_alter_rating_ratingvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ratingvalue',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
