# Generated by Django 5.0.1 on 2024-03-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0039_alter_rating_ratingvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
